name: CI

on:
  push:
    branches:
      - pathplanner
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13.1

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python3 -m pip install robotpy
          python3 -m robotpy sync

      - name: Run mypy
        run: |
          source venv/bin/activate
          mypy .
